### PR TITLE
Feat/interactive seg

### PR DESCRIPTION
**Pull request by summelon**
Hi, I open a new pull request for a cleaner review.

I have done the following:
- Solve conflicts b/t interactive seg. and new video seg.
- Clean up commits
- Add an introduction for interactive functionality in the readme.

BTW, maybe it's a good idea to split the js part into several small files.
It's suffering to solve conflicts on a large file.

### CODE REVIEW

**Comment by lujiazho** [comment]
Good features! Most seem to work well except the interactive seg does not support video seg anymore. The code is messy because I simultaneously maintain two paths: drawnPath and oriDrawnPath, where the former one is just for image seg and is in scaled size, and the latter one is for video seg and is in the original size. This is essential because if we just resize all the masks in drawnPath to the original size, the interpolated values cannot be used as masks for XMem. 

Anyway, I will merge your contribution. I will later consider adding interactive segs to the oriDrawnPath or completely removing the drawnPath and only keeping the oriDrawnPath. Thanks again!

**Comment by summelon** [comment]
Thanks for the merge!

For the bug on the video seg, I am sorry I did not test this part cause I can only test on a low-end CPU.
I did notice the diff b/t oriDrawnPath and drawnPath and handle them separately.
You may check on __line 417~437__ and __line 341 ~ 351__ of the HTML file to see if I mistook anything.
Specifically, I use `interactivePaths` to keep all masks in one interactive seg. session.
I think maybe I missed some handling of this for the video seg. part.

On the other hand, I have some suggestions for the repo.
1. It would be helpful to support multi-hierarchy (interactive segmentation). This may need some enhancements on the JS part. But I am a JS newbie, so I totally have no idea about this.
2. Other tools like AnyLabeling support onnx model for a faster experience. Also, I saw someone suggested to support FastSAM. Maybe I can help to enhance this part someday.

That's all. Feel free to ask if you need further help!
Cheers.

**Comment by lujiazho** [comment]
No worries! I already fixed the video seg. problem by adding a new variable `oriInteractivePaths`, which I know is trivial but I just do it to make it simple for now.

1. Can you explain more about multi-hierarchy (interactive segmentation)? I thought the positive and negative prompts are already interactive, aren't they? By the way, I'm also no expert on the front-end stuff, just have fun.
2. ONNX support and FastSAM, where the former one may require some time to learn new things but I got something else to do recently. As for the FastSAM, it should be relatively simpler, where probably a new button on the front end may be needed to shift the model.

I'm always working at a slow pace on this little project. If you'd like to add new features, feel free to do it and have fun!

**Comment by lujiazho** [comment]
1. I see. Probably too fancy for a simple static web page. A more advanced framework may fit this better. I guess the feature of seg-everything can somehow get a fine-grained segmentation.
2. This sounds great! Feel free to enhance this part and I guess I can learn much from your contribution!

**Pull request merged**
