### PR TITLE
Added python requirements.txt for easy setup and typo fixes

### PR DESCRIPTION
**Pull request by JairajJangle**
As PR #4 seems to be stale, here is a new PR with updated requirements.txt created with `pip freeze`.

### CODE REVIEW

**Comment by JairajJangle** [comment]
@lujiazho can we merge this PR?

**Comment by lujiazho** [comment]
Thanks for your effort! But there might be something missing, e.g. moviepy, which is used in video propagation. I'm not sure if there is more. Could you please double-check?

**Comment by JairajJangle** [comment]
@lujiazho I will check and update the PR, thanks for the feedback.

**Comment by JairajJangle** [comment]
@lujiazho I have updated the PR with the suggested changes and also fixed some minor typo issues in the project.

**Pull request merged**
