### PR TITLE
Add interactive segmentation

### PR DESCRIPTION
**Pull request by summelon**
Hi, thanks for your great web UI and backend.
It's a pity that it does not support interactive segmentation as the official demo.
I added this part to your codebase.
Could you review my change and is there anything else I need to do?

### CODE REVIEW

**Review by lujiazho — CHANGES_REQUESTED** [review]
Thanks for your effort to make the repo clean and neat and for additional function enhancement! But before adding video seg operation and reorganize the HTML code, I didn't notice your contribution. Sorry I cannot merge your updates for now, which may cause conflicts. If not too much trouble could you revisit your code modifications and submit a new commit? If not possible it's ok, I will check your code when I get some spare time. Very much appreciate your understanding and cooperation in this matter!

**Comment by summelon** [comment]
Hi, Thanks for your reply.
I will manage to solve the conflict these days.
Also, I am considering adding a video to show the usage of the interactive segmentation I added.
Is there anything else I need to take care?

**Comment by lujiazho** [comment]
> Hi, Thanks for your reply. I will manage to solve the conflict these days. Also, I am considering adding a video to show the usage of the interactive segmentation I added. Is there anything else I need to take care?

No concern! I won't change the source code recently. Feel free to add text or video intro to the coming new feature!

**Comment by summelon** [comment]
Reopened in #11

**Pull request closed without merging**
